In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


<h1><b>Central Tendency</b></h1>

In [5]:
m = np.random.randint(2,7,20)
print(m)

[5 3 2 6 2 5 6 2 4 4 5 4 2 6 5 3 5 2 3 5]


In [8]:
mean = np.mean(m)
print("the mean of the data is:",mean)

the mean of the data is: 3.95


In [9]:
median = np.median(m)
print("the median of the data is:",median)

the median of the data is: 4.0


<h2>Keep in Mind</h2><br>
Mode is not a part of the numpy library and must be imported from library statistics only.

In [11]:
from statistics import mode
print("the mode of the data is:", mode(m))

the mode of the data is: 5


In [12]:
population = np.random.randint(2,50,100)
population


array([11, 18,  9, 17,  2,  6, 49, 19, 17, 48, 26, 38, 43, 47, 43, 49,  7,
       41, 41, 32, 27, 20, 37, 26, 29, 29, 34, 17, 10,  7, 37, 36,  3, 26,
       41, 26, 12, 29, 20, 23, 35, 47, 44,  9, 27, 47, 45,  7, 38,  2, 37,
        6, 13, 19, 33, 40, 41, 47,  3, 40, 34, 32, 46, 41, 25, 38, 47, 20,
       39, 12, 27, 47, 23,  2, 36, 23, 15, 17, 35,  6, 44, 29,  8, 38,  2,
        8, 19, 18,  3,  8, 33, 46,  2, 33,  9,  9, 45, 15,  8, 33])

In [14]:
sample = np.random.choice(population, 20)
sample


array([ 6, 39,  2, 39, 29, 47, 33, 35, 32,  6, 33, 26, 33, 18,  7, 45, 17,
       26, 46, 36])

In [15]:
np.mean(sample)

27.75

In [16]:
np.median(sample)

32.5

In [17]:
mode(sample)

33

In [18]:
sample_1=np.random.choice(population, 10)
sample_2=np.random.choice(population, 10)
sample_3=np.random.choice(population, 10)
sample_4=np.random.choice(population, 10)

In [20]:
all_samples = [sample_1, sample_2, sample_3, sample_4]
sample_mean=[]
for i in all_samples:
    sample_mean.append(np.mean(i))
    
sample_mean

[24.4, 30.9, 30.2, 28.5]