<h1><b>Measure of Spread</b></h1>

Measure of spread gives the variability in the data and how well the data is distributed.</br>
Can be divided into 4 parts:<br>
1)Range: It gives how well the data is spread out.<br>
2)Quartile: Quartiles divide the rank-ordered dataset into four equal parts <br>
3)Variance: Gives How Spread out the number is from its mean. <br>
4)Standard Deviation: The square root of variance is standard deviation. It gives the exact distances from the mean. <br>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

<h1>Finding Range</h1>

In [5]:
ran = np.random.randint(1,100,20)
ran

array([ 7, 95, 39, 93, 95, 35, 47, 72, 36, 33, 43, 92, 52, 22, 41,  4, 50,
       43, 72, 78])

In [7]:
print("the range is", np.max(ran)-np.min(ran))


the range is 91


<h1><b>Finding Quartile</b></h1>


In [9]:
q1 = np.percentile(ran,25)
q2 = np.percentile(ran,50)
q3 = np.percentile(ran, 75)
print("the first quartile is:", q1)
print("the second quartile is:",q2)
print("the third quartilr is:",q3)

the first quartile is: 35.75
the second quartile is: 45.0
the third quartilr is: 73.5


<h1><b>Finding Variance</b></h1>

In [11]:
population = np.random.randn(100)
population

array([ 0.95558285, -0.25564183,  0.89798806, -0.83684647,  0.08342897,
        0.5196084 ,  0.24023756,  0.06771973, -1.64460342, -1.90750921,
        2.64411734,  1.05874064,  2.28618227,  0.35291302, -0.71324138,
        0.24839547, -1.08152745,  0.77765037,  0.45080531, -0.00652329,
       -0.4788723 ,  0.18070028, -1.03190876, -0.53651381,  0.24933612,
        0.82380111, -0.39630067, -1.35100486, -1.32587904, -0.14848955,
       -2.05672183,  1.24182516,  0.27249345,  0.56645656,  1.88600923,
       -0.58679436, -1.45883584,  0.68068677, -1.94363294,  0.81249162,
        0.99675002, -1.0835164 , -1.23954337,  0.41444924,  1.0441298 ,
        0.53000373,  0.30289664, -0.63673405, -1.10610527, -2.1191253 ,
       -0.68192157, -0.44878527,  1.19709235,  0.413135  ,  1.18519225,
       -2.30807084, -0.90740911, -0.95498289, -0.31031408,  0.75102968,
        0.48301121,  0.37767341,  0.26294204,  2.13740056,  0.98920322,
       -0.57209836,  0.08671314, -0.42186839, -0.34666366,  0.61

In [13]:
sample = np.random.choice(population,30)
sample

array([-1.23954337,  1.0441298 , -1.64460342, -0.67082218,  0.44392275,
        1.64698204, -0.00652329,  0.77765037,  0.75102968, -2.30807084,
        1.24182516, -1.90750921, -1.03190876, -1.35100486, -0.44878527,
        0.30289664,  0.81129149, -0.57209836,  0.35291302,  0.44392275,
        0.89798806, -0.25564183,  1.05874064,  0.99675002,  0.41444924,
       -1.03190876, -0.57037922,  1.05874064, -0.31031408,  0.08520531])

In [14]:
np.mean(sample)

-0.03402252808109198

In [15]:
np.var(sample)

1.0198646530893385

<h1><b>Findind Standard Deviation</b></h1>

In [17]:
np.std(population)

1.0346760179016383

In [18]:
np.std(sample)

1.0098834849077087

In [22]:
import math as m

In [26]:
m.sqrt(np.var(population))

1.0346760179016383

In [27]:
m.sqrt(np.var(sample))

1.0098834849077087